### ISSUE TITLE
CAD files

### ISSUE THREAD

**Issue by drnedm** [toastfr35/KhordUino#1]
Hi,
thanks so much for sharing this project! I'm building the tensioner part to use it on an old existing drop-weight machine. In order to make an adapter plate, it would be super helpful to not only have the STLs but also an assembled CAD file, STEP format or similar. 
Would you be willing to share that as well?

Cheers,
D

**Comment by toastfr35** [comment]
Hi, the source is all OpenSCAD but the code is quite a mess at the moment. Let me know which STLs you need and I'll clean these first and put them online.

**Comment by drnedm** [comment]
Great, thanks again!

openSCAD is also perfectly fine, I'd be fine with messy openSCAD as well.

For me personally the whole tensioner assembly is relevant, while the rotating racket mount part is not.

**Comment by drnedm** [comment]
So from the manual I think that would be

EB.stl
MB.stl
TS_body.stl
TS_top.stl
GS_body.stl
GS_springs_housing.stl
GS_fixed_jaw.stl
GS_mobile_jaw.stl
GS_mobile_jaw_retainer.stl

**Comment by toastfr35** [comment]
Here they are in the SCADs directory.  Not super-clean but I'll improve this later.
